// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pingcli_command.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProtoPingCliCommand_Configuration_FullMethodName = "/proto.ProtoPingCliCommand/Configuration"
	ProtoPingCliCommand_Run_FullMethodName           = "/proto.ProtoPingCliCommand/Run"
)

// ProtoPingCliCommandClient is the client API for ProtoPingCliCommand service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtoPingCliCommandClient interface {
	Configuration(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigurationResponse, error)
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*Empty, error)
}

type protoPingCliCommandClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoPingCliCommandClient(cc grpc.ClientConnInterface) ProtoPingCliCommandClient {
	return &protoPingCliCommandClient{cc}
}

func (c *protoPingCliCommandClient) Configuration(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigurationResponse)
	err := c.cc.Invoke(ctx, ProtoPingCliCommand_Configuration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoPingCliCommandClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProtoPingCliCommand_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoPingCliCommandServer is the server API for ProtoPingCliCommand service.
// All implementations must embed UnimplementedProtoPingCliCommandServer
// for forward compatibility.
type ProtoPingCliCommandServer interface {
	Configuration(context.Context, *Empty) (*ConfigurationResponse, error)
	Run(context.Context, *RunRequest) (*Empty, error)
	mustEmbedUnimplementedProtoPingCliCommandServer()
}

// UnimplementedProtoPingCliCommandServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtoPingCliCommandServer struct{}

func (UnimplementedProtoPingCliCommandServer) Configuration(context.Context, *Empty) (*ConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configuration not implemented")
}
func (UnimplementedProtoPingCliCommandServer) Run(context.Context, *RunRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedProtoPingCliCommandServer) mustEmbedUnimplementedProtoPingCliCommandServer() {}
func (UnimplementedProtoPingCliCommandServer) testEmbeddedByValue()                             {}

// UnsafeProtoPingCliCommandServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtoPingCliCommandServer will
// result in compilation errors.
type UnsafeProtoPingCliCommandServer interface {
	mustEmbedUnimplementedProtoPingCliCommandServer()
}

func RegisterProtoPingCliCommandServer(s grpc.ServiceRegistrar, srv ProtoPingCliCommandServer) {
	// If the following call pancis, it indicates UnimplementedProtoPingCliCommandServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtoPingCliCommand_ServiceDesc, srv)
}

func _ProtoPingCliCommand_Configuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoPingCliCommandServer).Configuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoPingCliCommand_Configuration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoPingCliCommandServer).Configuration(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoPingCliCommand_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoPingCliCommandServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoPingCliCommand_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoPingCliCommandServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtoPingCliCommand_ServiceDesc is the grpc.ServiceDesc for ProtoPingCliCommand service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtoPingCliCommand_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProtoPingCliCommand",
	HandlerType: (*ProtoPingCliCommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configuration",
			Handler:    _ProtoPingCliCommand_Configuration_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _ProtoPingCliCommand_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pingcli_command.proto",
}
