// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pingcli_command.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pingcli_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pingcli_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pingcli_command_proto_rawDescGZIP(), []int{0}
}

type ConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Example       string                 `protobuf:"bytes,3,opt,name=example,proto3" json:"example,omitempty"`
	Long          string                 `protobuf:"bytes,4,opt,name=long,proto3" json:"long,omitempty"`
	Short         string                 `protobuf:"bytes,5,opt,name=short,proto3" json:"short,omitempty"`
	Use           string                 `protobuf:"bytes,6,opt,name=use,proto3" json:"use,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationResponse) Reset() {
	*x = ConfigurationResponse{}
	mi := &file_pingcli_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationResponse) ProtoMessage() {}

func (x *ConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pingcli_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_pingcli_command_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigurationResponse) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *ConfigurationResponse) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *ConfigurationResponse) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *ConfigurationResponse) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_pingcli_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingcli_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_pingcli_command_proto_rawDescGZIP(), []int{2}
}

func (x *RunRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_pingcli_command_proto protoreflect.FileDescriptor

const file_pingcli_command_proto_rawDesc = "" +
	"\n" +
	"\x15pingcli_command.proto\x12\x05proto\"\a\n" +
	"\x05Empty\"m\n" +
	"\x15ConfigurationResponse\x12\x18\n" +
	"\aexample\x18\x03 \x01(\tR\aexample\x12\x12\n" +
	"\x04long\x18\x04 \x01(\tR\x04long\x12\x14\n" +
	"\x05short\x18\x05 \x01(\tR\x05short\x12\x10\n" +
	"\x03use\x18\x06 \x01(\tR\x03use\" \n" +
	"\n" +
	"RunRequest\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args2z\n" +
	"\x13ProtoPingCliCommand\x12;\n" +
	"\rConfiguration\x12\f.proto.Empty\x1a\x1c.proto.ConfigurationResponse\x12&\n" +
	"\x03Run\x12\x11.proto.RunRequest\x1a\f.proto.EmptyB\tZ\a./protob\x06proto3"

var (
	file_pingcli_command_proto_rawDescOnce sync.Once
	file_pingcli_command_proto_rawDescData []byte
)

func file_pingcli_command_proto_rawDescGZIP() []byte {
	file_pingcli_command_proto_rawDescOnce.Do(func() {
		file_pingcli_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pingcli_command_proto_rawDesc), len(file_pingcli_command_proto_rawDesc)))
	})
	return file_pingcli_command_proto_rawDescData
}

var file_pingcli_command_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pingcli_command_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: proto.Empty
	(*ConfigurationResponse)(nil), // 1: proto.ConfigurationResponse
	(*RunRequest)(nil),            // 2: proto.RunRequest
}
var file_pingcli_command_proto_depIdxs = []int32{
	0, // 0: proto.ProtoPingCliCommand.Configuration:input_type -> proto.Empty
	2, // 1: proto.ProtoPingCliCommand.Run:input_type -> proto.RunRequest
	1, // 2: proto.ProtoPingCliCommand.Configuration:output_type -> proto.ConfigurationResponse
	0, // 3: proto.ProtoPingCliCommand.Run:output_type -> proto.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pingcli_command_proto_init() }
func file_pingcli_command_proto_init() {
	if File_pingcli_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pingcli_command_proto_rawDesc), len(file_pingcli_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pingcli_command_proto_goTypes,
		DependencyIndexes: file_pingcli_command_proto_depIdxs,
		MessageInfos:      file_pingcli_command_proto_msgTypes,
	}.Build()
	File_pingcli_command_proto = out.File
	file_pingcli_command_proto_goTypes = nil
	file_pingcli_command_proto_depIdxs = nil
}
