// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: pingcli_command.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pingcli_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pingcli_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pingcli_command_proto_rawDescGZIP(), []int{0}
}

type LoggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggerRequest) Reset() {
	*x = LoggerRequest{}
	mi := &file_pingcli_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggerRequest) ProtoMessage() {}

func (x *LoggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingcli_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggerRequest.ProtoReflect.Descriptor instead.
func (*LoggerRequest) Descriptor() ([]byte, []int) {
	return file_pingcli_command_proto_rawDescGZIP(), []int{1}
}

func (x *LoggerRequest) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *LoggerRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type PingCliCommandConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Example       *string                `protobuf:"bytes,1,opt,name=example" json:"example,omitempty"`
	Long          *string                `protobuf:"bytes,2,opt,name=long" json:"long,omitempty"`
	Short         *string                `protobuf:"bytes,3,opt,name=short" json:"short,omitempty"`
	Use           *string                `protobuf:"bytes,4,opt,name=use" json:"use,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingCliCommandConfigurationResponse) Reset() {
	*x = PingCliCommandConfigurationResponse{}
	mi := &file_pingcli_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCliCommandConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCliCommandConfigurationResponse) ProtoMessage() {}

func (x *PingCliCommandConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pingcli_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCliCommandConfigurationResponse.ProtoReflect.Descriptor instead.
func (*PingCliCommandConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_pingcli_command_proto_rawDescGZIP(), []int{2}
}

func (x *PingCliCommandConfigurationResponse) GetExample() string {
	if x != nil && x.Example != nil {
		return *x.Example
	}
	return ""
}

func (x *PingCliCommandConfigurationResponse) GetLong() string {
	if x != nil && x.Long != nil {
		return *x.Long
	}
	return ""
}

func (x *PingCliCommandConfigurationResponse) GetShort() string {
	if x != nil && x.Short != nil {
		return *x.Short
	}
	return ""
}

func (x *PingCliCommandConfigurationResponse) GetUse() string {
	if x != nil && x.Use != nil {
		return *x.Use
	}
	return ""
}

type PingCliCommandRunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Args           []string               `protobuf:"bytes,1,rep,name=args" json:"args,omitempty"`
	Logger         *uint32                `protobuf:"varint,2,opt,name=logger" json:"logger,omitempty"`
	Authentication *uint32                `protobuf:"varint,3,opt,name=authentication" json:"authentication,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingCliCommandRunRequest) Reset() {
	*x = PingCliCommandRunRequest{}
	mi := &file_pingcli_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCliCommandRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCliCommandRunRequest) ProtoMessage() {}

func (x *PingCliCommandRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingcli_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCliCommandRunRequest.ProtoReflect.Descriptor instead.
func (*PingCliCommandRunRequest) Descriptor() ([]byte, []int) {
	return file_pingcli_command_proto_rawDescGZIP(), []int{3}
}

func (x *PingCliCommandRunRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *PingCliCommandRunRequest) GetLogger() uint32 {
	if x != nil && x.Logger != nil {
		return *x.Logger
	}
	return 0
}

func (x *PingCliCommandRunRequest) GetAuthentication() uint32 {
	if x != nil && x.Authentication != nil {
		return *x.Authentication
	}
	return 0
}

type AuthenticationToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *string                `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	TokenType     *string                `protobuf:"bytes,2,opt,name=token_type,json=tokenType" json:"token_type,omitempty"`
	Expiry        *int64                 `protobuf:"varint,3,opt,name=expiry" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationToken) Reset() {
	*x = AuthenticationToken{}
	mi := &file_pingcli_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationToken) ProtoMessage() {}

func (x *AuthenticationToken) ProtoReflect() protoreflect.Message {
	mi := &file_pingcli_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationToken.ProtoReflect.Descriptor instead.
func (*AuthenticationToken) Descriptor() ([]byte, []int) {
	return file_pingcli_command_proto_rawDescGZIP(), []int{4}
}

func (x *AuthenticationToken) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *AuthenticationToken) GetTokenType() string {
	if x != nil && x.TokenType != nil {
		return *x.TokenType
	}
	return ""
}

func (x *AuthenticationToken) GetExpiry() int64 {
	if x != nil && x.Expiry != nil {
		return *x.Expiry
	}
	return 0
}

var File_pingcli_command_proto protoreflect.FileDescriptor

const file_pingcli_command_proto_rawDesc = "" +
	"\n" +
	"\x15pingcli_command.proto\"\a\n" +
	"\x05Empty\"\x98\x01\n" +
	"\rLoggerRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x122\n" +
	"\x06fields\x18\x02 \x03(\v2\x1a.LoggerRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"#PingCliCommandConfigurationResponse\x12\x18\n" +
	"\aexample\x18\x01 \x01(\tR\aexample\x12\x12\n" +
	"\x04long\x18\x02 \x01(\tR\x04long\x12\x14\n" +
	"\x05short\x18\x03 \x01(\tR\x05short\x12\x10\n" +
	"\x03use\x18\x04 \x01(\tR\x03use\"n\n" +
	"\x18PingCliCommandRunRequest\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x12\x16\n" +
	"\x06logger\x18\x02 \x01(\rR\x06logger\x12&\n" +
	"\x0eauthentication\x18\x03 \x01(\rR\x0eauthentication\"o\n" +
	"\x13AuthenticationToken\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\x03R\x06expiry2y\n" +
	"\x0ePingCliCommand\x12=\n" +
	"\rConfiguration\x12\x06.Empty\x1a$.PingCliCommandConfigurationResponse\x12(\n" +
	"\x03Run\x12\x19.PingCliCommandRunRequest\x1a\x06.Empty2\xdf\x01\n" +
	"\x06Logger\x12!\n" +
	"\aMessage\x12\x0e.LoggerRequest\x1a\x06.Empty\x12!\n" +
	"\aSuccess\x12\x0e.LoggerRequest\x1a\x06.Empty\x12\x1e\n" +
	"\x04Warn\x12\x0e.LoggerRequest\x1a\x06.Empty\x12#\n" +
	"\tUserError\x12\x0e.LoggerRequest\x1a\x06.Empty\x12#\n" +
	"\tUserFatal\x12\x0e.LoggerRequest\x1a\x06.Empty\x12%\n" +
	"\vPluginError\x12\x0e.LoggerRequest\x1a\x06.Empty2:\n" +
	"\x0eAuthentication\x12(\n" +
	"\bGetToken\x12\x06.Empty\x1a\x14.AuthenticationTokenB\tZ\a./protob\beditionsp\xe8\a"

var (
	file_pingcli_command_proto_rawDescOnce sync.Once
	file_pingcli_command_proto_rawDescData []byte
)

func file_pingcli_command_proto_rawDescGZIP() []byte {
	file_pingcli_command_proto_rawDescOnce.Do(func() {
		file_pingcli_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pingcli_command_proto_rawDesc), len(file_pingcli_command_proto_rawDesc)))
	})
	return file_pingcli_command_proto_rawDescData
}

var file_pingcli_command_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pingcli_command_proto_goTypes = []any{
	(*Empty)(nil),         // 0: Empty
	(*LoggerRequest)(nil), // 1: LoggerRequest
	(*PingCliCommandConfigurationResponse)(nil), // 2: PingCliCommandConfigurationResponse
	(*PingCliCommandRunRequest)(nil),            // 3: PingCliCommandRunRequest
	(*AuthenticationToken)(nil),                 // 4: AuthenticationToken
	nil,                                         // 5: LoggerRequest.FieldsEntry
}
var file_pingcli_command_proto_depIdxs = []int32{
	5,  // 0: LoggerRequest.fields:type_name -> LoggerRequest.FieldsEntry
	0,  // 1: PingCliCommand.Configuration:input_type -> Empty
	3,  // 2: PingCliCommand.Run:input_type -> PingCliCommandRunRequest
	1,  // 3: Logger.Message:input_type -> LoggerRequest
	1,  // 4: Logger.Success:input_type -> LoggerRequest
	1,  // 5: Logger.Warn:input_type -> LoggerRequest
	1,  // 6: Logger.UserError:input_type -> LoggerRequest
	1,  // 7: Logger.UserFatal:input_type -> LoggerRequest
	1,  // 8: Logger.PluginError:input_type -> LoggerRequest
	0,  // 9: Authentication.GetToken:input_type -> Empty
	2,  // 10: PingCliCommand.Configuration:output_type -> PingCliCommandConfigurationResponse
	0,  // 11: PingCliCommand.Run:output_type -> Empty
	0,  // 12: Logger.Message:output_type -> Empty
	0,  // 13: Logger.Success:output_type -> Empty
	0,  // 14: Logger.Warn:output_type -> Empty
	0,  // 15: Logger.UserError:output_type -> Empty
	0,  // 16: Logger.UserFatal:output_type -> Empty
	0,  // 17: Logger.PluginError:output_type -> Empty
	4,  // 18: Authentication.GetToken:output_type -> AuthenticationToken
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pingcli_command_proto_init() }
func file_pingcli_command_proto_init() {
	if File_pingcli_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pingcli_command_proto_rawDesc), len(file_pingcli_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pingcli_command_proto_goTypes,
		DependencyIndexes: file_pingcli_command_proto_depIdxs,
		MessageInfos:      file_pingcli_command_proto_msgTypes,
	}.Build()
	File_pingcli_command_proto = out.File
	file_pingcli_command_proto_goTypes = nil
	file_pingcli_command_proto_depIdxs = nil
}
