// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pingcli_command.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pingcli_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pingcli_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pingcli_command_proto_rawDescGZIP(), []int{0}
}

type LoggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggerRequest) Reset() {
	*x = LoggerRequest{}
	mi := &file_pingcli_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggerRequest) ProtoMessage() {}

func (x *LoggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingcli_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggerRequest.ProtoReflect.Descriptor instead.
func (*LoggerRequest) Descriptor() ([]byte, []int) {
	return file_pingcli_command_proto_rawDescGZIP(), []int{1}
}

func (x *LoggerRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoggerRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type PingCliCommandConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Example       string                 `protobuf:"bytes,1,opt,name=example,proto3" json:"example,omitempty"`
	Long          string                 `protobuf:"bytes,2,opt,name=long,proto3" json:"long,omitempty"`
	Short         string                 `protobuf:"bytes,3,opt,name=short,proto3" json:"short,omitempty"`
	Use           string                 `protobuf:"bytes,4,opt,name=use,proto3" json:"use,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingCliCommandConfigurationResponse) Reset() {
	*x = PingCliCommandConfigurationResponse{}
	mi := &file_pingcli_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCliCommandConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCliCommandConfigurationResponse) ProtoMessage() {}

func (x *PingCliCommandConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pingcli_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCliCommandConfigurationResponse.ProtoReflect.Descriptor instead.
func (*PingCliCommandConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_pingcli_command_proto_rawDescGZIP(), []int{2}
}

func (x *PingCliCommandConfigurationResponse) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *PingCliCommandConfigurationResponse) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *PingCliCommandConfigurationResponse) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *PingCliCommandConfigurationResponse) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

type PingCliCommandRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Logger        uint32                 `protobuf:"varint,2,opt,name=logger,proto3" json:"logger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingCliCommandRunRequest) Reset() {
	*x = PingCliCommandRunRequest{}
	mi := &file_pingcli_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCliCommandRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCliCommandRunRequest) ProtoMessage() {}

func (x *PingCliCommandRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingcli_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCliCommandRunRequest.ProtoReflect.Descriptor instead.
func (*PingCliCommandRunRequest) Descriptor() ([]byte, []int) {
	return file_pingcli_command_proto_rawDescGZIP(), []int{3}
}

func (x *PingCliCommandRunRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *PingCliCommandRunRequest) GetLogger() uint32 {
	if x != nil {
		return x.Logger
	}
	return 0
}

var File_pingcli_command_proto protoreflect.FileDescriptor

const file_pingcli_command_proto_rawDesc = "" +
	"\n" +
	"\x15pingcli_command.proto\x12\x05proto\"\a\n" +
	"\x05Empty\"\x9e\x01\n" +
	"\rLoggerRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x128\n" +
	"\x06fields\x18\x02 \x03(\v2 .proto.LoggerRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"#PingCliCommandConfigurationResponse\x12\x18\n" +
	"\aexample\x18\x01 \x01(\tR\aexample\x12\x12\n" +
	"\x04long\x18\x02 \x01(\tR\x04long\x12\x14\n" +
	"\x05short\x18\x03 \x01(\tR\x05short\x12\x10\n" +
	"\x03use\x18\x04 \x01(\tR\x03use\"F\n" +
	"\x18PingCliCommandRunRequest\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x12\x16\n" +
	"\x06logger\x18\x02 \x01(\rR\x06logger2\x91\x01\n" +
	"\x0ePingCliCommand\x12I\n" +
	"\rConfiguration\x12\f.proto.Empty\x1a*.proto.PingCliCommandConfigurationResponse\x124\n" +
	"\x03Run\x12\x1f.proto.PingCliCommandRunRequest\x1a\f.proto.Empty2\xa7\x02\n" +
	"\x06Logger\x12-\n" +
	"\aMessage\x12\x14.proto.LoggerRequest\x1a\f.proto.Empty\x12-\n" +
	"\aSuccess\x12\x14.proto.LoggerRequest\x1a\f.proto.Empty\x12*\n" +
	"\x04Warn\x12\x14.proto.LoggerRequest\x1a\f.proto.Empty\x12/\n" +
	"\tUserError\x12\x14.proto.LoggerRequest\x1a\f.proto.Empty\x12/\n" +
	"\tUserFatal\x12\x14.proto.LoggerRequest\x1a\f.proto.Empty\x121\n" +
	"\vPluginError\x12\x14.proto.LoggerRequest\x1a\f.proto.EmptyB\tZ\a./protob\x06proto3"

var (
	file_pingcli_command_proto_rawDescOnce sync.Once
	file_pingcli_command_proto_rawDescData []byte
)

func file_pingcli_command_proto_rawDescGZIP() []byte {
	file_pingcli_command_proto_rawDescOnce.Do(func() {
		file_pingcli_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pingcli_command_proto_rawDesc), len(file_pingcli_command_proto_rawDesc)))
	})
	return file_pingcli_command_proto_rawDescData
}

var file_pingcli_command_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pingcli_command_proto_goTypes = []any{
	(*Empty)(nil),         // 0: proto.Empty
	(*LoggerRequest)(nil), // 1: proto.LoggerRequest
	(*PingCliCommandConfigurationResponse)(nil), // 2: proto.PingCliCommandConfigurationResponse
	(*PingCliCommandRunRequest)(nil),            // 3: proto.PingCliCommandRunRequest
	nil,                                         // 4: proto.LoggerRequest.FieldsEntry
}
var file_pingcli_command_proto_depIdxs = []int32{
	4, // 0: proto.LoggerRequest.fields:type_name -> proto.LoggerRequest.FieldsEntry
	0, // 1: proto.PingCliCommand.Configuration:input_type -> proto.Empty
	3, // 2: proto.PingCliCommand.Run:input_type -> proto.PingCliCommandRunRequest
	1, // 3: proto.Logger.Message:input_type -> proto.LoggerRequest
	1, // 4: proto.Logger.Success:input_type -> proto.LoggerRequest
	1, // 5: proto.Logger.Warn:input_type -> proto.LoggerRequest
	1, // 6: proto.Logger.UserError:input_type -> proto.LoggerRequest
	1, // 7: proto.Logger.UserFatal:input_type -> proto.LoggerRequest
	1, // 8: proto.Logger.PluginError:input_type -> proto.LoggerRequest
	2, // 9: proto.PingCliCommand.Configuration:output_type -> proto.PingCliCommandConfigurationResponse
	0, // 10: proto.PingCliCommand.Run:output_type -> proto.Empty
	0, // 11: proto.Logger.Message:output_type -> proto.Empty
	0, // 12: proto.Logger.Success:output_type -> proto.Empty
	0, // 13: proto.Logger.Warn:output_type -> proto.Empty
	0, // 14: proto.Logger.UserError:output_type -> proto.Empty
	0, // 15: proto.Logger.UserFatal:output_type -> proto.Empty
	0, // 16: proto.Logger.PluginError:output_type -> proto.Empty
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pingcli_command_proto_init() }
func file_pingcli_command_proto_init() {
	if File_pingcli_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pingcli_command_proto_rawDesc), len(file_pingcli_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pingcli_command_proto_goTypes,
		DependencyIndexes: file_pingcli_command_proto_depIdxs,
		MessageInfos:      file_pingcli_command_proto_msgTypes,
	}.Build()
	File_pingcli_command_proto = out.File
	file_pingcli_command_proto_goTypes = nil
	file_pingcli_command_proto_depIdxs = nil
}
