version: "2"
linters:
  default: all
  disable:
    - bodyclose # Checks whether HTTP response body is closed successfully.
    - containedctx # Containedctx is a linter that detects struct contained context.Context field.
    - contextcheck # Check whether the function uses a non-inherited context.
    - cyclop # Checks function and package cyclomatic complexity.
    - depguard # 	Go linter that checks if package imports are in a list of acceptable packages.
    - dupl # Detects duplicate fragments of code.
    - err113 # Go linter to check the errors handling expressions.
    - exhaustive # Check exhaustiveness of enum switch statements.
    - exhaustruct # Checks if all structure fields are initialized.
    - fatcontext # Detects nested contexts in loops and function literals.
    - forbidigo # Forbids identifiers.
    - funlen # Checks for long functions.
    - gochecknoinits # Checks that no init functions are present in Go code.
    - gochecknoglobals # Check that no global variables exist.
    - gocognit # Computes and checks the cognitive complexity of functions.
    - goconst # Finds repeated strings that could be replaced by a constant.
    - gocyclo # Computes and checks the cyclomatic complexity of functions.
    - godot # Check if comments end in a period.
    - godox # Detects usage of FIXME, TODO and other keywords inside comments.
    - lll # Reports long lines.
    - loggercheck # Checks key value pairs for common logger libraries (kitlog,klog,logr,zap).
    - maintidx # Maintidx measures the maintainability index of each function.
    - mnd # An analyzer to detect magic numbers.
    - nestif # Reports deeply nested if statements.
    - nonamedreturns # Reports all named returns.
    - paralleltest # 	Detects missing usage of t.Parallel() method in your Go test.
    - perfsprint # Checks that fmt.Sprintf can be replaced with a faster alternative.
    - promlinter # Check Prometheus metrics naming via promlint.
    - recvcheck # Checks for receiver type consistency.
    - revive # Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint.
    - sloglint # Ensure consistent code style when using log/slog.
    - spancheck # Checks for mistakes with OpenTelemetry/Census spans.
    - sqlclosecheck # Checks that sql.Rows, sql.Stmt, sqlx.NamedStmt, pgx.Query are closed.
    - tagliatelle # Checks the struct tags.
    - testifylint # Checks usage of github.com/stretchr/testify.
    - varnamelen # Checks that the length of a variable's name matches its scope.
    - wrapcheck # Checks that errors returned from external packages are wrapped.
    - wsl # Add or remove empty lines.
