= pingcli config
:created-date: September 18, 2026
:revdate: September 18, 2026
:resourceid: pingcli_command_reference_pingcli_config

Manage the CLI configuration.

== Synopsis

Manage the configuration of the CLI, including Ping product connection parameters.

The Ping CLI supports the use of configuration profiles.
Configuration profiles can be used when connecting to multiple environments using the same Ping CLI instance, such as when managing multiple development or demonstration environments.

A pre-defined default profile will be used to store the configuration of the CLI.
Additional custom profiles can be created using the `pingcli config add-profile` command.
To use a custom profile, the `--profile` flag can be used on supported commands to specify the profile to use for that command.
To set a custom profile as the default, use the `pingcli config set-active-profile` command.

----
pingcli config
----

== Options

----
  -U, --unmask-values   Unmask secret values. (default false)
  -h, --help            help for config
----

== Options inherited from parent commands

----
  -C, --config string          The relative or full path to a custom Ping CLI configuration file. (default $HOME/.pingcli/config.yaml)
  -D, --detailed-exitcode      Enable detailed exit code output. (default false) 0 - pingcli command succeeded with no errors or warnings. 1 - pingcli command failed with errors. 2 - pingcli command succeeded with warnings.
  -O, --output-format string   Specify the console output format. (default text) Options are: json, text.
  -P, --profile string         The name of a configuration profile to use.
      --no-color               Disable text output in color. (default false)
----

== More information

* xref:pingcli.adoc[]	 - A CLI tool for managing the configuration of Ping Identity products.

== Subcommands

* xref:pingcli_config_add-profile.adoc[] - Add a new custom configuration profile.
* xref:pingcli_config_delete-profile.adoc[] - Delete a custom configuration profile.
* xref:pingcli_config_get.adoc[] - Read stored configuration settings for the CLI.
* xref:pingcli_config_list-keys.adoc[] - List all configuration keys.
* xref:pingcli_config_list-profiles.adoc[] - List all custom configuration profiles.
* xref:pingcli_config_set.adoc[] - Set stored configuration settings for the CLI.
* xref:pingcli_config_set-active-profile.adoc[] - Set a custom configuration profile as the in-use profile.
* xref:pingcli_config_unset.adoc[] - Unset stored configuration settings for the CLI.
* xref:pingcli_config_view-profile.adoc[] - View the stored configuration of a custom configuration profile.

