// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package pingone_testable_resources

import (
	"testing"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/connector/pingone/platform/resources"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
)

func GatewayRoleAssignment(t *testing.T, clientInfo *connector.ClientInfo) *testutils_resource.TestableResource {
	t.Helper()

	return &testutils_resource.TestableResource{
		ClientInfo: clientInfo,
		CreateFunc: createGatewayRoleAssignment,
		DeleteFunc: deleteGatewayRoleAssignment,
		Dependencies: []*testutils_resource.TestableResource{
			Gateway(t, clientInfo),
		},
		ExportableResource: resources.GatewayRoleAssignment(clientInfo),
	}
}

func createGatewayRoleAssignment(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, strArgs ...string) testutils_resource.ResourceCreationInfo {
	t.Helper()

	if len(strArgs) != 1 {
		t.Fatalf("Unexpected number of arguments provided to createGatewayRoleAssignment(): %v", strArgs)
	}
	gatewayId := strArgs[0]

	iter := clientInfo.PingOneApiClient.ManagementAPIClient.RolesApi.ReadAllRoles(clientInfo.PingOneContext).Execute()
	roles, err := pingone.GetManagementAPIObjectsFromIterator[management.Role](iter, "ReadAllRoles", "GetRoles", resourceType)
	if err != nil {
		t.Fatalf("Failed to execute PingOne client function\nError: %v", err)
	}
	if len(roles) == 0 {
		t.Fatalf("Failed to execute PingOne client function\n No built-in roles returned from ReadAllRoles()", err)
	}

	// Use a random role
	roleId := roles[0].Id
	roleName := roles[0].Name

	request := clientInfo.PingOneApiClient.ManagementAPIClient.GatewayRoleAssignmentsApi.CreateGatewayRoleAssignment(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, gatewayId)
	clientStruct := management.RoleAssignment{
		Role: management.RoleAssignmentRole{
			Id: *roleId,
		},
		Scope: management.RoleAssignmentScope{
			Id:   clientInfo.PingOneExportEnvironmentID,
			Type: "ENVIRONMENT",
		},
	}

	request = request.RoleAssignment(clientStruct)

	resource, response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "CreateGatewayRoleAssignment", resourceType)
	if err != nil {
		t.Fatalf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)
	}
	if !ok {
		t.Fatalf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)
	}

	return testutils_resource.ResourceCreationInfo{
		DepIds: []string{
			gatewayId,
		},
		SelfInfo: map[testutils_resource.ResourceCreationInfoType]string{
			testutils_resource.ENUM_ID:   *resource.Id,
			testutils_resource.ENUM_NAME: string(*roleName),
		},
	}
}

func deleteGatewayRoleAssignment(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, ids ...string) {
	t.Helper()

	if len(ids) != 2 {
		t.Fatalf("Unexpected number of arguments provided to deleteGatewayRoleAssignment(): %v", ids)
	}
	gatewayId := ids[0]
	gatewayRoleAssignmentId := ids[1]

	request := clientInfo.PingOneApiClient.ManagementAPIClient.GatewayRoleAssignmentsApi.DeleteGatewayRoleAssignment(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, gatewayId, gatewayRoleAssignmentId)

	response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "DeleteGatewayRoleAssignment", resourceType)
	if err != nil {
		t.Fatalf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)
	}
	if !ok {
		t.Fatalf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)
	}
}
