// Copyright © 2026 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources

import (
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/logger"
)

// Verify that the resource satisfies the exportable resource interface
var (
	_ connector.ExportableResource = &PingOneAdministratorSecurityResource{}
)

type PingOneAdministratorSecurityResource struct {
	clientInfo *connector.ClientInfo
}

// Utility method for creating a PingOneAdministratorSecurityResource
func AdministratorSecurity(clientInfo *connector.ClientInfo) *PingOneAdministratorSecurityResource {
	return &PingOneAdministratorSecurityResource{
		clientInfo: clientInfo,
	}
}

func (r *PingOneAdministratorSecurityResource) ResourceType() string {
	return "pingone_administrator_security"
}

func (r *PingOneAdministratorSecurityResource) ExportAll() (*[]connector.ImportBlock, error) {
	l := logger.Get()
	l.Debug().Msgf("Exporting all '%s' Resources...", r.ResourceType())

	importBlocks := make([]connector.ImportBlock, 0, 1)

	ok, err := r.checkAdministratorSecurityData()
	if err != nil {
		return nil, err
	}
	if !ok {
		return &importBlocks, nil
	}

	commentData := map[string]string{
		"Resource Type":         r.ResourceType(),
		"Export Environment ID": r.clientInfo.PingOneExportEnvironmentID,
	}

	importBlock := connector.ImportBlock{
		ResourceType:       r.ResourceType(),
		ResourceName:       r.ResourceType(),
		ResourceID:         r.clientInfo.PingOneExportEnvironmentID,
		CommentInformation: common.GenerateCommentInformation(commentData),
	}

	importBlocks = append(importBlocks, importBlock)

	return &importBlocks, nil
}

func (r *PingOneAdministratorSecurityResource) checkAdministratorSecurityData() (bool, error) {
	_, response, err := r.clientInfo.PingOneApiClient.ManagementAPIClient.AdministratorSecurityApi.ReadAdministratorSecurity(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID).Execute()

	return common.CheckSingletonResource(response, err, "ReadAdministratorSecurity", r.ResourceType())
}
