// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources

import (
	"fmt"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/logger"
)

// Verify that the resource satisfies the exportable resource interface
var (
	_ connector.ExportableResource = &PingOneCustomRoleResource{}
)

type PingOneCustomRoleResource struct {
	clientInfo *connector.ClientInfo
}

// Utility method for creating a PingOneCustomRoleResource
func CustomRole(clientInfo *connector.ClientInfo) *PingOneCustomRoleResource {
	return &PingOneCustomRoleResource{
		clientInfo: clientInfo,
	}
}

func (r *PingOneCustomRoleResource) ResourceType() string {
	return "pingone_custom_role"
}

func (r *PingOneCustomRoleResource) ExportAll() (*[]connector.ImportBlock, error) {
	l := logger.Get()
	l.Debug().Msgf("Exporting all '%s' Resources...", r.ResourceType())

	importBlocks := make([]connector.ImportBlock, 0, 1)

	customRoleData, err := r.getCustomRoleData()
	if err != nil {
		return nil, err
	}

	for customRoleId, customRoleName := range customRoleData {
		commentData := map[string]string{
			"Custom Role ID":        customRoleId,
			"Custom Role Name":      customRoleName,
			"Export Environment ID": r.clientInfo.PingOneExportEnvironmentID,
			"Resource Type":         r.ResourceType(),
		}

		importBlock := connector.ImportBlock{
			ResourceType:       r.ResourceType(),
			ResourceName:       customRoleName,
			ResourceID:         fmt.Sprintf("%s/%s", r.clientInfo.PingOneExportEnvironmentID, customRoleId),
			CommentInformation: common.GenerateCommentInformation(commentData),
		}

		importBlocks = append(importBlocks, importBlock)
	}

	return &importBlocks, nil
}

func (r *PingOneCustomRoleResource) getCustomRoleData() (map[string]string, error) {
	customRoleData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.ManagementAPIClient.CustomAdminRolesApi.ReadAllCustomAdminRoles(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.EntityArrayEmbeddedRolesInner](iter, "ReadAllCustomAdminRoles", "GetRoles", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, innerObj := range apiObjs {
		if innerObj.CustomAdminRole != nil {
			customRoleId, customRoleIdOk := innerObj.CustomAdminRole.GetIdOk()
			customRoleName, customRoleNameOk := innerObj.CustomAdminRole.GetNameOk()

			if customRoleIdOk && customRoleNameOk {
				customRoleData[*customRoleId] = *customRoleName
			}
		}
	}

	return customRoleData, nil
}
