// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources_test

// Commented out due to current PingOne Client Error
// func Test_Form(t *testing.T) {
// 	clientInfo := testutils.GetClientInfo(t)

// 	tr := pingone_platform_testable_resources.Form(t, clientInfo)

// 	tr.CreateResource(t)
// 	defer tr.DeleteResource(t)

// 	expectedImportBlocks := []connector.ImportBlock{
// 		{
// 			ResourceType: tr.ExportableResource.ResourceType(),
// 			ResourceName: tr.ResourceInfo.CreationInfo[testutils_resource.ENUM_NAME],
// 			ResourceID:   fmt.Sprintf("%s/%s", clientInfo.PingOneExportEnvironmentID, tr.ResourceInfo.CreationInfo[testutils_resource.ENUM_ID]),
// 		},
// 	}

// 	testutils.ValidateImportBlocks(t, tr.ExportableResource, &expectedImportBlocks)
// }
