// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources

import (
	"fmt"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/logger"
)

// Verify that the resource satisfies the exportable resource interface
var (
	_ connector.ExportableResource = &PingOneKeyResource{}
)

type PingOneKeyResource struct {
	clientInfo *connector.ClientInfo
}

// Utility method for creating a PingOneKeyResource
func Key(clientInfo *connector.ClientInfo) *PingOneKeyResource {
	return &PingOneKeyResource{
		clientInfo: clientInfo,
	}
}

func (r *PingOneKeyResource) ResourceType() string {
	return "pingone_key"
}

func (r *PingOneKeyResource) ExportAll() (*[]connector.ImportBlock, error) {
	l := logger.Get()
	l.Debug().Msgf("Exporting all '%s' Resources...", r.ResourceType())

	importBlocks := []connector.ImportBlock{}

	keyData, err := r.getKeyData()
	if err != nil {
		return nil, err
	}

	for keyId, keyName := range keyData {
		commentData := map[string]string{
			"Key ID":                keyId,
			"Key Name":              keyName,
			"Export Environment ID": r.clientInfo.PingOneExportEnvironmentID,
			"Resource Type":         r.ResourceType(),
		}

		importBlock := connector.ImportBlock{
			ResourceType:       r.ResourceType(),
			ResourceName:       keyName,
			ResourceID:         fmt.Sprintf("%s/%s", r.clientInfo.PingOneExportEnvironmentID, keyId),
			CommentInformation: common.GenerateCommentInformation(commentData),
		}

		importBlocks = append(importBlocks, importBlock)
	}

	return &importBlocks, nil
}

func (r *PingOneKeyResource) getKeyData() (map[string]string, error) {
	keyData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.ManagementAPIClient.CertificateManagementApi.GetKeys(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.Certificate](iter, "GetKeys", "GetKeys", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, key := range apiObjs {
		keyId, keyIdOk := key.GetIdOk()
		keyName, keyNameOk := key.GetNameOk()

		if keyIdOk && keyNameOk {
			keyData[*keyId] = *keyName
		}
	}

	return keyData, nil
}
