// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources

import (
	"fmt"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/logger"
)

// Verify that the resource satisfies the exportable resource interface
var (
	_ connector.ExportableResource = &PingOneLangaugeResource{}
)

type PingOneLangaugeResource struct {
	clientInfo *connector.ClientInfo
}

// Utility method for creating a PingOneLangaugeResource
func Langauge(clientInfo *connector.ClientInfo) *PingOneLangaugeResource {
	return &PingOneLangaugeResource{
		clientInfo: clientInfo,
	}
}

func (r *PingOneLangaugeResource) ResourceType() string {
	return "pingone_langauge"
}

func (r *PingOneLangaugeResource) ExportAll() (*[]connector.ImportBlock, error) {
	l := logger.Get()
	l.Debug().Msgf("Exporting all '%s' Resources...", r.ResourceType())

	importBlocks := []connector.ImportBlock{}

	langaugeData, err := r.getLangaugeData()
	if err != nil {
		return nil, err
	}

	for langaugeId, langaugeName := range langaugeData {
		commentData := map[string]string{
			"Langauge ID":           langaugeId,
			"Langauge Name":         langaugeName,
			"Export Environment ID": r.clientInfo.PingOneExportEnvironmentID,
			"Resource Type":         r.ResourceType(),
		}

		importBlock := connector.ImportBlock{
			ResourceType:       r.ResourceType(),
			ResourceName:       langaugeName,
			ResourceID:         fmt.Sprintf("%s/%s", r.clientInfo.PingOneExportEnvironmentID, langaugeId),
			CommentInformation: common.GenerateCommentInformation(commentData),
		}

		importBlocks = append(importBlocks, importBlock)
	}

	return &importBlocks, nil
}

func (r *PingOneLangaugeResource) getLangaugeData() (map[string]string, error) {
	langaugeData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.ManagementAPIClient.LanguagesApi.ReadLanguages(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.EntityArrayEmbeddedLanguagesInner](iter, "ReadLanguages", "GetLanguages", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, innerObj := range apiObjs {
		if innerObj.Language != nil {
			langaugeId, langaugeIdOk := inner.Language.GetIdOk()
			langaugeName, langaugeNameOk := inner.Language.GetNameOk()

			if langaugeIdOk && langaugeNameOk {
				langaugeData[*langaugeId] = *langaugeName
			}
		}
	}

	return langaugeData, nil
}
