// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources_test

import (
	"fmt"
	"testing"

	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/testing/testutils"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource/pingone_testable_resources"
)

func Test_NotificationTemplateContent(t *testing.T) {
	clientInfo := testutils.GetClientInfo(t)

	tr := pingone_testable_resources.NotificationTemplateContent(t, clientInfo)

	creationInfo := tr.CreateResource(t)
	defer tr.DeleteResource(t)

	expectedImportBlocks := []connector.ImportBlock{
		{
			ResourceType: tr.ExportableResource.ResourceType(),
			ResourceName: fmt.Sprintf("%s_%s_%s_%s_%s", creationInfo.SelfInfo[testutils_resource.ENUM_NAME], creationInfo.SelfInfo[testutils_resource.ENUM_TEMPLATE_DELIVERY_METHOD], creationInfo.SelfInfo[testutils_resource.ENUM_LOCALE], creationInfo.SelfInfo[testutils_resource.ENUM_TEMPLATE_VARIANT], creationInfo.SelfInfo[testutils_resource.ENUM_ID]),
			ResourceID:   fmt.Sprintf("%s/%s/%s", clientInfo.PingOneExportEnvironmentID, creationInfo.SelfInfo[testutils_resource.ENUM_NAME], creationInfo.SelfInfo[testutils_resource.ENUM_ID]),
		},
	}

	// There are pre-configured notification template contents in the environment, so only validate the import blocks as a subset.
	testutils.ValidateImportBlockSubset(t, tr.ExportableResource, &expectedImportBlocks)
}
