// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources

import (
	"fmt"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/logger"
)

// Verify that the resource satisfies the exportable resource interface
var (
	_ connector.ExportableResource = &PingOneIdentityProviderResource{}
)

type PingOneIdentityProviderResource struct {
	clientInfo *connector.ClientInfo
}

// Utility method for creating a PingOneIdentityProviderResource
func IdentityProvider(clientInfo *connector.ClientInfo) *PingOneIdentityProviderResource {
	return &PingOneIdentityProviderResource{
		clientInfo: clientInfo,
	}
}

func (r *PingOneIdentityProviderResource) ResourceType() string {
	return "pingone_identity_provider"
}

func (r *PingOneIdentityProviderResource) ExportAll() (*[]connector.ImportBlock, error) {
	l := logger.Get()
	l.Debug().Msgf("Exporting all '%s' Resources...", r.ResourceType())

	importBlocks := []connector.ImportBlock{}

	identityProviderData, err := r.getIdentityProviderData()
	if err != nil {
		return nil, err
	}

	for identityProviderId, identityProviderName := range identityProviderData {
		commentData := map[string]string{
			"Identity Provider ID":   identityProviderId,
			"Identity Provider Name": identityProviderName,
			"Export Environment ID":  r.clientInfo.PingOneExportEnvironmentID,
			"Resource Type":          r.ResourceType(),
		}

		importBlock := connector.ImportBlock{
			ResourceType:       r.ResourceType(),
			ResourceName:       identityProviderName,
			ResourceID:         fmt.Sprintf("%s/%s", r.clientInfo.PingOneExportEnvironmentID, identityProviderId),
			CommentInformation: common.GenerateCommentInformation(commentData),
		}

		importBlocks = append(importBlocks, importBlock)
	}

	return &importBlocks, nil
}

func (r *PingOneIdentityProviderResource) getIdentityProviderData() (map[string]string, error) {
	identityProviderData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.ManagementAPIClient.IdentityProvidersApi.ReadAllIdentityProviders(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.IdentityProvider](iter, "ReadAllIdentityProviders", "GetIdentityProviders", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, inner := range apiObjs {
		var (
			identityProviderId     *string
			identityProviderIdOk   bool
			identityProviderName   *string
			identityProviderNameOk bool
		)

		switch {
		case inner.IdentityProviderApple != nil:
			identityProviderId, identityProviderIdOk = inner.IdentityProviderApple.GetIdOk()
			identityProviderName, identityProviderNameOk = inner.IdentityProviderApple.GetNameOk()
		case inner.IdentityProviderClientIDClientSecret != nil:
			identityProviderId, identityProviderIdOk = inner.IdentityProviderClientIDClientSecret.GetIdOk()
			identityProviderName, identityProviderNameOk = inner.IdentityProviderClientIDClientSecret.GetNameOk()
		case inner.IdentityProviderFacebook != nil:
			identityProviderId, identityProviderIdOk = inner.IdentityProviderFacebook.GetIdOk()
			identityProviderName, identityProviderNameOk = inner.IdentityProviderFacebook.GetNameOk()
		case inner.IdentityProviderOIDC != nil:
			identityProviderId, identityProviderIdOk = inner.IdentityProviderOIDC.GetIdOk()
			identityProviderName, identityProviderNameOk = inner.IdentityProviderOIDC.GetNameOk()
		case inner.IdentityProviderPaypal != nil:
			identityProviderId, identityProviderIdOk = inner.IdentityProviderPaypal.GetIdOk()
			identityProviderName, identityProviderNameOk = inner.IdentityProviderPaypal.GetNameOk()
		case inner.IdentityProviderSAML != nil:
			identityProviderId, identityProviderIdOk = inner.IdentityProviderSAML.GetIdOk()
			identityProviderName, identityProviderNameOk = inner.IdentityProviderSAML.GetNameOk()
		default:
			continue
		}

		if identityProviderIdOk && identityProviderNameOk {
			identityProviderData[*identityProviderId] = *identityProviderName
		}
	}

	return identityProviderData, nil
}
